/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CrsRouteImport } from './routes/crs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CrsRoute = CrsRouteImport.update({
  id: '/crs',
  path: '/crs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/crs': typeof CrsRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/crs': typeof CrsRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/crs': typeof CrsRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/announcements'
    | '/auth'
    | '/crs'
    | '/events'
    | '/faculty'
    | '/sitemap.xml'
    | '/timetable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/announcements'
    | '/auth'
    | '/crs'
    | '/events'
    | '/faculty'
    | '/sitemap.xml'
    | '/timetable'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/announcements'
    | '/auth'
    | '/crs'
    | '/events'
    | '/faculty'
    | '/sitemap.xml'
    | '/timetable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuthRoute: typeof AuthRoute
  CrsRoute: typeof CrsRoute
  EventsRoute: typeof EventsRoute
  FacultyRoute: typeof FacultyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TimetableRoute: typeof TimetableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crs': {
      id: '/crs'
      path: '/crs'
      fullPath: '/crs'
      preLoaderRoute: typeof CrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AuthRoute: AuthRoute,
  CrsRoute: CrsRoute,
  EventsRoute: EventsRoute,
  FacultyRoute: FacultyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TimetableRoute: TimetableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
