/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'

const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/announcements' | '/events' | '/faculty' | '/timetable'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/announcements' | '/events' | '/faculty' | '/timetable'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/events'
    | '/faculty'
    | '/timetable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  EventsRoute: typeof EventsRoute
  FacultyRoute: typeof FacultyRoute
  TimetableRoute: typeof TimetableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  EventsRoute: EventsRoute,
  FacultyRoute: FacultyRoute,
  TimetableRoute: TimetableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
